"""drawbridge-init-config: generate a deployment configuration skeleton.

Borrowed from the reference implementation's bootstrap command, adapted to
this repository's four-file bundle: copies the repository's operation and
workflow catalogs verbatim (they are code-coupled and reviewed together)
and generates ``drawbridge.yaml`` / ``apps.yaml`` / the Compose template
anchored at an operator-supplied root directory, with explicit
``REPLACE_*`` placeholders for the values only the administrator knows
(repo origin, BuildKit socket, frozen test image id).

Idempotence: refuses to overwrite any existing file in the target
directory — regeneration means a new directory.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

_REPLACE_HINTS = (
    "Manual steps before first use:",
    "1. apps.yaml: set git.repo_path to the pre-cloned repository and git.origin",
    "   to its real origin URL (local mirror or ssh/https).",
    "2. apps.yaml: point buildkit_socket at the rootless buildkitd socket and",
    "   replace the frozen test image id (docker image inspect, sha256:...).",
    "3. drawbridge.yaml: tighten allowed_cidrs/allowed_hosts to your segment.",
    "4. Install the compose template and scripts under /etc/drawbridge (see",
    "   docs/DEPLOYMENT.md), then run drawbridge-selfcheck.",
)

_MAIN_TEMPLATE = """\
# Generated by drawbridge-init-config — edit before first use.
# Deployment guide: docs/DEPLOYMENT.md
schema_version: 1

server:
  bind_address: 0.0.0.0
  port: {port}
  base_path: /mcp
  allowed_cidrs:
    - "{cidr}"
  allowed_origins:
    - "http://{host}:{port}"
  allowed_hosts:
    - "{host}:{port}"
  auth:
    mode: none                   # switch to `token` for shared-secret checks
    token_file: {root}/etc/token

paths:
  state_dir: {root}/var/lib
  lock_dir: {root}/run/locks
  log_dir: {root}/var/log
  config_dir: {root}/etc

toolchain:
  git: /usr/bin/git
  docker: /usr/bin/docker
  ps: /usr/bin/ps
  buildctl: /usr/local/bin/buildctl

profile_env:
  source_manage:
    home: {root}/var/lib/home/source
  runtime_manage:
    home: {root}/var/lib/home/runtime
  host_observe:
    home: {root}/var/lib/home/observe
  project_diagnostic:
    home: {root}/var/lib/home/diagnostic

concurrency:
  max_read_requests: 16
  max_running_jobs: 1
  max_queued_jobs: 50
  max_queued_jobs_per_target: 5
  queue_timeout_seconds: 600
  min_deploy_interval_seconds: 60

diagnostics:
  max_concurrent: 16
  retention_seconds: 86400
  wait_budget_seconds: 25

output:
  query_summary_max_bytes: 65536
  log_result_max_lines: 200
  log_result_max_bytes: 262144
  step_log_soft_limit_bytes: 1048576     # reserved, not enforced (D9 deviation)
  step_log_hard_limit_bytes: 20971520
  job_log_hard_limit_bytes: 104857600    # reserved, not enforced (D9 deviation)

maintenance:
  enabled: false

retention:
  cleanup_interval_seconds: 3600
  idempotency_key_days: 7
  plan_days: 7
  job_record_days: 7

recovery:
  stale_running_job_seconds: 900
"""

_APPS_TEMPLATE = """\
# Generated by drawbridge-init-config — replace every REPLACE_* placeholder.
schema_version: 1

apps:
  demo:
    git:
      repo_path: {root}/repos/demo
      origin: REPLACE_WITH_REPO_ORIGIN
      allowed_ref_patterns:
        - '^refs/heads/main$'
        - '^refs/heads/agent/[A-Za-z0-9_-]+$'
      tags_enabled: false
    npu:
      enabled: false
    environments:
      staging:
        runtime: compose
        project_name: drawbridge-demo-staging
        build_profile: demo
        buildkit_socket: REPLACE_WITH_BUILDKIT_SOCKET
        deploy_root: {root}/apps/demo/staging
        compose_file: {root}/etc/compose/demo.staging.yaml
        health_checks:
          - type: http
            url: http://127.0.0.1:18080/healthz
            expected_status: 200
            timeout_seconds: 90
            single_timeout_seconds: 3
            interval_seconds: 2
            consecutive_successes: 3
        services: [api]
        restartable_services: [api]
        test_suites: [smoke]
        test_runner:
          smoke:
            image_id: REPLACE_WITH_FROZEN_TEST_IMAGE_ID
            entrypoint: /opt/drawbridge/suites/demo/smoke
            timeout_seconds: 300
            network: drawbridge-demo-test
            resources:
              cpus: "1"
              memory: 512m
              pids_limit: 128
        diagnostics:
          # an EXISTING directory (the registered repo works); never
          # deploy_root/current — it is never created (plan D14 trap)
          root: {root}/repos/demo
          config_files:
            app_config:
              path: config/app.json
              raw: false
              fields: [name, listen_port, log_level]
              sensitive_fields: [admin_token]
          validators:                     # RESERVED: not executed by code yet
            json_syntax:                   # (config_validate is JSON/TOML only)
              executable: /usr/bin/python3
              argv: ["-m", "json.tool"]
              timeout_seconds: 15
        retention:
          successful_releases: 5
          job_logs_days: 7
        disk_budget_bytes: 10737418240

build_profiles:
  demo:
    context: .
    dockerfile_basename: Dockerfile
    platform: linux/arm64
    timeout_seconds: 900
    max_parallel: 1
    import_timeout_seconds: 300
"""

_COMPOSE_TEMPLATE = """\
# Compose template — admin-side configuration; Drawbridge rewrites only the
# image reference to the release's frozen immutable image ID.
# The image token below must appear EXACTLY ONCE (raw-text count, comments
# included).  Multiple services sharing one image must use a YAML anchor
# (x-image: &img <token> / image: *img) rather than repeating the token.
services:
  api:
    image: REPLACE_BY_DRAWBRIDGE
    ports:
      - "18080:8080"
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=64m
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    user: "65532:65532"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512m
    pids_limit: 128
    restart: unless-stopped
"""

_EMPTY_ENV_TEMPLATE = """\\
# Drawbridge compose interpolation pin — DELIBERATELY EMPTY (plan D13).
# Passed as --env-file on every compose invocation so no project-directory
# .env is ever loaded implicitly; business secrets belong in the admin
# template's env_file: directives.
"""


def _default_source_config_dir() -> Path | None:
    candidate = Path(__file__).resolve().parents[3] / "configs"
    if (candidate / "operations.yaml").is_file():
        return candidate
    return None


def init_config(
    target_dir: Path,
    *,
    root: Path,
    host: str,
    port: int,
    cidr: str,
    source_config_dir: Path,
) -> list[Path]:
    """Write the skeleton; returns the created files in order."""
    files = {
        "drawbridge.yaml": _MAIN_TEMPLATE.format(
            root=root.as_posix(), host=host, port=port, cidr=cidr
        ),
        "apps.yaml": _APPS_TEMPLATE.format(root=root.as_posix()),
    }
    existing = [
        name
        for name in (*files, "operations.yaml", "workflows.yaml")
        if (target_dir / name).exists()
    ]
    if existing:
        raise FileExistsError(
            f"refusing to overwrite existing files in {target_dir}: {existing}; "
            "choose a fresh directory"
        )
    target_dir.mkdir(parents=True, exist_ok=True)
    created: list[Path] = []
    for name in ("operations.yaml", "workflows.yaml"):
        destination = target_dir / name
        shutil.copyfile(source_config_dir / name, destination)
        created.append(destination)
    for name, content in files.items():
        destination = target_dir / name
        destination.write_text(content, encoding="utf-8")
        created.append(destination)
    compose_dir = target_dir / "compose"
    compose_dir.mkdir(exist_ok=True)
    compose = compose_dir / "demo.staging.yaml"
    compose.write_text(_COMPOSE_TEMPLATE, encoding="utf-8")
    created.append(compose)
    empty_env = compose_dir / "empty.env"
    empty_env.write_text(_EMPTY_ENV_TEMPLATE, encoding="utf-8")
    created.append(empty_env)
    return created


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="drawbridge-init-config",
        description="Generate a deployment configuration skeleton (four YAMLs + compose template).",
    )
    parser.add_argument("target_dir", type=Path, help="directory to create the bundle in")
    parser.add_argument(
        "--root",
        type=Path,
        required=True,
        help="deployment root the generated paths anchor to (e.g. /srv/drawbridge)",
    )
    parser.add_argument("--host", default="192.168.18.7", help="server address clients use")
    parser.add_argument("--port", type=int, default=8787)
    parser.add_argument("--cidr", default="192.168.0.0/16", help="client source allowlist")
    parser.add_argument(
        "--source-config-dir",
        default=None,
        help="bundle to copy operations/workflows from (default: repository configs/)",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_arg_parser().parse_args(argv)
    source = (
        Path(args.source_config_dir) if args.source_config_dir else _default_source_config_dir()
    )
    if source is None or not (source / "operations.yaml").is_file():
        print(
            "cannot locate a source config bundle; pass --source-config-dir or "
            "run from the repository",
            file=sys.stderr,
        )
        return 2
    try:
        created = init_config(
            args.target_dir,
            root=args.root,
            host=args.host,
            port=args.port,
            cidr=args.cidr,
            source_config_dir=source,
        )
    except FileExistsError as exc:
        print(str(exc), file=sys.stderr)
        return 3
    except OSError as exc:
        print(f"cannot write the bundle: {exc}", file=sys.stderr)
        return 1
    for path in created:
        print(path)
    print(*_REPLACE_HINTS, sep="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
